version: 2.1

executors:
  build-test-deploy-executor:
    docker:
      - image: circleci/node:8.10.0
    working_directory: ~/build-test-deploy

jobs:
  build_base:
    executor: build-test-deploy-executor
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - node-modules-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - node-modules-{{ .Branch }}
            - node-modules-master
      - run: yarn install
      - save_cache:
          key: node-modules-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

  test_unit:
    executor: build-test-deploy-executor
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - node-modules-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run: yarn test

  build_app:
    executor: build-test-deploy-executor
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - node-modules-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - attach_workspace:
          at: ~/build-test-deploy
      - run: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - dist/compiled-ts

  run:
    executor: build-test-deploy-executor
    environment:
      SAY_HELLO_TO: World
    steps:
      - attach_workspace:
          at: ~/build-test-deploy
      - run: node dist/compiled-ts/index.js

workflows:
  build-test-deploy:
    jobs:
      - build_base
      - build_app:
          requires:
            - build_base
      - test_unit:
          requires:
            - build_base
      - run:
          requires:
            - build_app
            - test_unit
