version: 2.1

executors:
  build-test-deploy-executor:
    docker:
      - image: circleci/node:8.10.0
    working_directory: ~/build-test-deploy

jobs:
  build_base:
    executor: build-test-deploy-executor
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-{{ .Branch }}
            - yarn-packages-master
      - run: yarn install
      - save_cache:
          key: yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

  test_unit:
    executor: build-test-deploy-executor
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run: yarn test

  build_app:
    executor: build-test-deploy-executor
    steps:
      - attach_workspace:
          at: ~/build-test-deploy
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - dist/compiled-ts

  run:
    executor: build-test-deploy-executor
    steps:
      - attach_workspace:
          at: ~/build-test-deploy
      - run: node dist/compiled-ts/index.js

workflows:
  build-test-deploy:
    jobs:
      - build_base
      - build_app:
          requires:
            - build_base
      - test_unit:
          requires:
            - build_base
      - run:
          requires:
            - build_app
            - test_unit
